name: My CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init -backend-config="key=${AWS_ACCESS_KEY_ID},secret=${AWS_SECRET_ACCESS_KEY},region=${AWS_REGION}"

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Run tests
        run: |
          python3 -m unittest tests.py

      - name: Archive the function code
        uses: actions/upload-artifact@v3
        with:
          name: lambda_code
          path: |
            lambda_function.py

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: lambda_code

      - name: Create a ZIP archive of the function code
        run: zip -r lambda_code.zip lambda_code/*

      - name: Deploy the Lambda function
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          function-name: my-lambda-function
          zip-file: lambda_code.zip
          create-function: true
